---

- hosts: all
  tasks:
  - name: ajout des Groupes locaux
    block:
     - name : Ajout des Groupes Primaires
       group:
        name: "{{ item }}"
        state: present
       with_items: "{{ users | map(attribute='primary_group') | list | unique }}"


  - name: Ajout des utilisateurs
    user: 
     name: "{{ item.username }}"
     group: "{{ item.primary_group}}"
     home:  "{{ item.home | default('/home/' + item.username) }}"
     shell: "{{ item.shell | default('/bin/bash') }}"
     password: "{{ item.password | default('') }}"
     state: present
    with_items: "{{ users }}"
 
    
